### PR TITLE
rename resolve to findIntents

### LINKED ISSUE #36: Rename resolve method
The `resolve` method for the `DesktopAgent` interface is generically named. I propose that it be renamed to `queryIntents`, `queryActions`, `findIntents`, `findActions`, or something similar.

### PR DESCRIPTION
**Pull request by keshaldesai**
Rename `resolve` to `findIntents` to resolve #36

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@keshaldesai). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by ColinEberhardt** [comment]
I think the terminology in the specification doc will need updating too: https://github.com/FDC3/API/blob/master/Specification-Draft.MD#221-intent-resolution

**Comment by nkolba** [comment]
@keshaldesai the changes look good to me.  Can you sign the cla so that we can merge the PR?  @finos-admin Rob or Mao should be able to help if needed.

**Comment by keshaldesai** [comment]
@nkolba Sure thing. I'll work to get our CLA in.

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Pull request merged**
